title: Jake Sakamoto
logo: /assets/img/my-photo.jpg
description: Passionate student who loves to learn new things in Computer Science and Robotics! Love working on projects and keen interest in systems and computer vision!
#show_downloads: true
theme: jekyll-theme-minimal
